# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class AutogptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.autogptService = channel.stream_stream(
                '/grpc.autogpt.Autogpt/autogptService',
                request_serializer=message__pb2.AutogptRequest.SerializeToString,
                response_deserializer=message__pb2.AutogptResponse.FromString,
                )


class AutogptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def autogptService(self, request_iterator, context):
        """Makes a phone call and communicate states via a stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutogptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'autogptService': grpc.stream_stream_rpc_method_handler(
                    servicer.autogptService,
                    request_deserializer=message__pb2.AutogptRequest.FromString,
                    response_serializer=message__pb2.AutogptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.autogpt.Autogpt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Autogpt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def autogptService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc.autogpt.Autogpt/autogptService',
            message__pb2.AutogptRequest.SerializeToString,
            message__pb2.AutogptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
