# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.1"

services:
  auto-gpt:
    image: autogpt:${AUTOGPT_VERSION}
    ports:
      - 3005:4005
    command: /bin/bash -c "python -m autogpt -c -l 15"
    depends_on:
      - redis
    volumes:
      - ".env:/home/appuser/.env"
      - "./logs:/home/appuser/logs"
      - "./auto_gpt_workspace:/home/appuser/auto_gpt_workspace"

  redis:
    image: "redis/redis-stack-server:latest"

  autogpt_envoy:
    image: envoyproxy/envoy:v1.22.0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"

